## Site config ##
title: Lorem Ipsum
description: Your description
baseurl: "/" # Ex: /blog/
url: "" # Hostname
## Author config ##
author:
  twitter: loremipsum
  github:  loremipsum
  codepen: loremipsum
## Links configs ##
permalink: /blog/:title/
links:
  - title: Blog
    url: /blog/
## Other ##
highlighter: rouge
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src
