## Site config ##
title: Igor Oliveira
description: Desenvolvedor Web e Ux Design em Formação
baseurl: "/"
url: "https://devigor.github.io"
## Author config ##
author:
  name: Igor Oliveira
  description: Oi, eu me chamo Igor!
  email: devigor.tere@gmail.com
  twitter: _devigor
  github:  devigor
  codepen: devigor
## Links configs ##
permalink: /:title
links:
  - title: Blog
    url: /blog/
  - title: Sobre
    url: /about/
  - title: Projetos
    url: /projetos/
## Other ##
highlighter: rouge
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src
